[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.variables]
NODE_ENV = "production"
SUPABASE_URL = "https://hgqcuesummlopvgfnces.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhncWN1ZXN1bW1sb3B2Z2ZuY2VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDI2MDQsImV4cCI6MjA2OTA3ODYwNH0.G7y7Ep2whkmtMZ-fHQr3VCGweQyRv4MS6AkpkDBtw08"
FRONTEND_URL = "https://frontend-ruby-two-50.vercel.app"