services:
  - type: web
    name: coffee-tracker-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/recipes.db
      - key: SEED_DATABASE
        value: true
    healthCheckPath: /api/health